[package]
name = "meipuru"
version = "0.1.0"
edition = "2024"

include = ["src/**/*", "build.rs", "bindings/**/*", "LICENSE", "README.md"]

exclude = [
    ".vscode",
    "test_data",
    "bindings/bin",
    "bindings/.clang-format",
    "bindings/taglib/.github",
    "bindings/taglib/tests",
    "bindings/taglib/examples",
    "bindings/taglib/doc",
]

[features]
default = []
dynamic = []

[build-dependencies]
cmake = "0.1.58"
